# ==============================================================================
#  GitHub Action: Build Android APK on Frontend Update
#
#  This workflow automates the process of building a debuggable Android APK
#  whenever changes are pushed to the 'frontend' directory in the 'main' branch.
#  The resulting APK is uploaded as a build artifact, suitable for testing.
# ==============================================================================

name: Build Android APK on Frontend Update

# ------------------------------------------------------------------------------
#  Triggers
#  Defines when this workflow will run.
# ------------------------------------------------------------------------------
on:
  push:
    branches:
      - main  # 1. Only run on pushes to the 'main' branch.
    paths:
      - 'frontend/**'   # 2. AND only if files inside the 'frontend' directory have changed.
      - '.github/workflows/android-release.yml' # Or if the workflow file itself is changed.

# ------------------------------------------------------------------------------
#  Jobs
#  A workflow run is made up of one or more jobs.
# ------------------------------------------------------------------------------
jobs:
  build-android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # -----------------
      #  1. SETUP ENVIRONMENT
      # -----------------
      - name: 1.1 Checkout Repository
        uses: actions/checkout@v4 # Use the latest version of the checkout action

      - name: 1.2 Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18' # A stable LTS version of Node.js
          cache: 'npm' # Enable caching for npm packages
          cache-dependency-path: '**/package-lock.json'

      - name: 1.3 Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # A popular, open-source distribution of OpenJDK
          java-version: '17' # Required by modern Android Gradle Plugin

      - name: 1.4 Setup Android SDK
        uses: android-actions/setup-android@v3

      # -----------------
      #  2. INSTALL DEPENDENCIES & BUILD WEB APP
      # -----------------
      - name: 2.1 Install Root Dependencies
        # Installs dependencies listed in the root package.json, like Capacitor CLI
        run: npm install

      - name: 2.2 Install Frontend Dependencies and Build
        # Navigates into the frontend directory, installs its dependencies, and runs the build script
        run: |
          cd frontend
          npm install
          npm run build

      # -----------------
      #  3. CAPACITOR & ANDROID BUILD
      # -----------------
      - name: 3.1 Install Capacitor Android Platform
        # Ensures the @capacitor/android package is available for the CLI
        run: npm install @capacitor/android

      - name: 3.2 Sync Web Assets to Android Project
        # Copies the built web assets from 'frontend/dist' into the native Android project
        run: npx cap sync android

      - name: 3.3 Grant execute permission for gradlew
        # Some CI environments might not have execute permissions on the Gradle wrapper script
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: 3.4 Build Debug APK
        # Builds the debug version of the APK. It's faster and doesn't require complex signing secrets.
        working-directory: ./android
        run: ./gradlew assembleDebug

      # -----------------
      #  4. UPLOAD ARTIFACT
      # -----------------
      - name: 4.1 Get Commit Info for Naming
        id: commit-info
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 4.2 Upload APK as Build Artifact
        # Uploads the generated APK, making it available for download from the Actions run page.
        uses: actions/upload-artifact@v4
        with:
          name: Thirteen-Game-Debug-Build-${{ steps.commit-info.outputs.short_sha }}
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7 # Keep the artifact for 7 days