# ==============================================================================
#  GitHub Action: Build Android APK on Any Update
#
#  This workflow automates building a debuggable Android APK whenever ANY
#  change is pushed to the 'main' branch.
# ==============================================================================

name: Build Android APK on Any Update to Main

# ------------------------------------------------------------------------------
#  Triggers
#  Defines when this workflow will run.
# ------------------------------------------------------------------------------
on:
  push:
    branches:
      - main  # 1. Triggers on any push to the 'main' branch.
              # 2. The 'paths' filter has been removed, so ALL file changes will trigger it.

# ------------------------------------------------------------------------------
#  Jobs
# ------------------------------------------------------------------------------
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # --- 1. SETUP ---
      - name: 1.1 Checkout Repository
        uses: actions/checkout@v4

      - name: 1.2 Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 1.3 Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 1.4 Setup Android SDK
        uses: android-actions/setup-android@v3

      # --- 2. BUILD ---
      - name: 2.1 Install Dependencies and Build Web App
        run: |
          npm install
          cd frontend
          npm install
          npm run build
          cd ..
      
      - name: 2.2 Install Capacitor Android and Sync
        run: |
          npm install @capacitor/android
          npx cap sync android
          
      - name: 2.3 Grant execute permission for gradlew
        run: chmod +x android/gradlew
      
      - name: 2.4 Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug
        
      # --- 3. UPLOAD ARTIFACT ---
      - name: 3.1 Get Commit Info for Naming
        id: commit-info
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 3.2 Upload APK as Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thirteen-Game-Debug-Build-${{ steps.commit-info.outputs.short_sha }}
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
