# ==============================================================================
#  GitHub Action: Build Android APK on Frontend Update
#
#  This workflow automates the process of building a debuggable Android APK
#  whenever changes are pushed to the 'frontend' directory in the 'main' branch.
#  The resulting APK is uploaded as a build artifact, suitable for testing.
# ==============================================================================

name: Build Android APK on Frontend Update

# ------------------------------------------------------------------------------
#  Triggers
#  Defines when this workflow will run.
# ------------------------------------------------------------------------------
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/android-release.yml'

# ------------------------------------------------------------------------------
#  Jobs
#  A workflow run is made up of one or more jobs.
# ------------------------------------------------------------------------------
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # -----------------
      #  1. SETUP ENVIRONMENT
      # -----------------
      - name: 1.1 Checkout Repository
        uses: actions/checkout@v4

      - name: 1.2 Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # <-- FIXED: Use Node.js v20 to meet Capacitor CLI requirements
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 1.3 Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 1.4 Setup Android SDK
        uses: android-actions/setup-android@v3

      # -----------------
      #  2. INSTALL DEPENDENCIES & BUILD WEB APP
      # -----------------
      - name: 2.1 Install Root Dependencies
        run: npm install

      - name: 2.2 Install Frontend Dependencies and Build
        run: |
          cd frontend
          npm install
          npm run build

      # -----------------
      #  3. CAPACITOR & ANDROID BUILD
      # -----------------
      - name: 3.1 Install Capacitor Android Platform
        run: npm install @capacitor/android

      - name: 3.2 Sync Web Assets to Android Project
        run: npx cap sync android

      - name: 3.3 Grant execute permission for gradlew
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: 3.4 Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      # -----------------
      #  4. UPLOAD ARTIFACT
      # -----------------
      - name: 4.1 Get Commit Info for Naming
        id: commit-info
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 4.2 Upload APK as Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thirteen-Game-Debug-Build-${{ steps.commit-info.outputs.short_sha }}
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
