# ==============================================================================
# 构建并发布 Release Workflow
#
# 触发器：每次向 main 分支推送时
# 功能：
#   1. 检出代码
#   2. 安装 JDK/Node.js/Android SDK
#   3. 安装依赖并打包前端
#   4. 同步 Capacitor
#   5. 解码并校验 Keystore
#   6. 签名打包 Release APK
#   7. 重命名 APK
#   8. 自动创建 GitHub Release
# ==============================================================================

name: 构建并发布 Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  KEYSTORE_B64:     ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
  KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  KEY_ALIAS:        ${{ secrets.ANDROID_KEY_ALIAS }}
  KEY_PASSWORD:     ${{ secrets.ANDROID_KEY_PASSWORD }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout 代码
        uses: actions/checkout@v4

      - name: 2. 安装 JDK (Temurin 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 安装 Node.js (v20) 并启用 npm 缓存
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 3. 安装 Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
          packages: |
            tools
            platform-tools
            build-tools;33.0.0
            platforms;android-33

      - name: 4. 安装前端依赖
        run: |
          npm install
          cd frontend
          npm install

      - name: 5. 构建前端 Web 应用
        run: npm run build -w frontend

      - name: 6. 同步 Capacitor (Android)
        run: npx cap sync android

      - name: 7. 解码并校验 Keystore
        run: |
          # 解码出 keystore
          echo "$KEYSTORE_B64" | base64 --decode > my-release-key.keystore

          # 检查文件大小 & 前 80 字节十六进制
          ls -lh my-release-key.keystore
          head -c 80 my-release-key.keystore | xxd

          # 用 keytool 列出别名，验证密码和 alias 都正确
          keytool -list -v \
            -keystore my-release-key.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias "$KEY_ALIAS"

          # 写入 SDK 路径，消除警告
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: 8. 授予 Gradle Wrapper 可执行权限
        run: chmod +x android/gradlew

      - name: 9. 生成版本号信息
        id: versioning
        run: |
          echo "version_name=dev-$(date +'%Y%m%d')-${{ github.sha_short }}" >> $GITHUB_OUTPUT
          echo "version_code=${{ github.run_number }}"            >> $GITHUB_OUTPUT

      - name: 10. 签名并打包 Release APK
        working-directory: android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file="${{ github.workspace }}/my-release-key.keystore" \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD" \
            -PappVersionCode=${{ steps.versioning.outputs.version_code }} \
            -PappVersionName=${{ steps.versioning.outputs.version_name }}

      - name: 11. 重命名 Release APK
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/摆牌-${{ steps.versioning.outputs.version_name }}.apk

      - name: 12. 自动创建 GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.sha }}
          name: 自动发布 ${{ steps.versioning.outputs.version_name }}
          artifacts: android/app/build/outputs/apk/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          body: |
            此版本由 GitHub Actions 自动生成  
            Commit: ${{ github.sha }}  
            版本名: ${{ steps.versioning.outputs.version_name }}  
            版本码: ${{ steps.versioning.outputs.version_code }}
