# ==============================================================================
#  GitHub Action: Create Release and Upload Signed APK
#
#  This workflow automates building a SIGNED, RELEASE-READY Android APK.
#  It triggers ONLY when a new tag matching 'v*.*.*' (e.g., v1.0.1) is pushed.
# ==============================================================================

name: Create GitHub Release with Signed APK

# ------------------------------------------------------------------------------
#  Triggers
# ------------------------------------------------------------------------------
on:
  push:
    tags:
      - 'v*.*.*' # IMPORTANT: Triggers only on version tags.

# ------------------------------------------------------------------------------
#  Jobs
# ------------------------------------------------------------------------------
jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      # --- 1. SETUP ---
      - name: 1.1 Checkout Repository
        uses: actions/checkout@v4

      - name: 1.2 Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 1.3 Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 1.4 Setup Android SDK
        uses: android-actions/setup-android@v3

      # --- 2. BUILD ---
      - name: 2.1 Install Dependencies and Build Web App
        run: |
          npm install
          cd frontend
          npm install
          npm run build
          cd ..
      
      - name: 2.2 Install Capacitor Android and Sync
        run: |
          npm install @capacitor/android
          npx cap sync android
          
      - name: 2.3 Decode and Place Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore

      - name: 2.4 Grant execute permission for gradlew
        run: chmod +x android/gradlew
      
      - name: 2.5 Build Signed Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file="${{ github.workspace }}/android/app/my-release-key.keystore" \
          -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
          -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
          -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
      
      # --- 3. RELEASE ---
      - name: 3.1 Rename APK for Release
        # The signed APK is named app-release.apk
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/Thirteen-Game-${{ github.ref_name }}.apk

      - name: 3.2 Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          files: android/app/build/outputs/apk/release/Thirteen-Game-*.apk
